# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'customers-test-app' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for customers-test-app
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'FBSDKLoginKit'
  pod 'Firebase/Analytics'
  pod 'Firebase/Database'
  pod 'MaterialComponents/Snackbar'

  target 'customers-test-appTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
